name: build library

on:
  pull_request:
    branches: [
      'release/angular-ui'
    ]

jobs:
  build_library:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://npm.pkg.github.com'
          scope: '@patricksalmeida'

      - name: Install dependencies
        run: npm install

      - name: Build library
        run: npx nx build angular-ui


